#Vehicles Attributes.
#TunerStudio by Philip Tobin
#Mon Aug 10 13:09:51 SGT 2026
converterStall=
injectorSize=295
firstGearRatio=
fourthGearRatio=
finalDriveRatio=
transmissionType=Manual
fifthGearRatio=
weight=
thirdGearRatio=
sixthGearRatio=
secondGearRatio=
engineDisplacement=1600
