#Vehicles Attributes.
#TunerStudio by Philip Tobin
#Wed Apr 08 13:43:17 SGT 2026
converterStall=
injectorSize=290
firstGearRatio=
fourthGearRatio=
finalDriveRatio=
transmissionType=Manual
fifthGearRatio=
weight=
thirdGearRatio=
sixthGearRatio=
secondGearRatio=
engineDisplacement=1600
